In [1]:
import sys
sys.path.insert(0, '/home/sahar.sagy/Project/PhysioAssist/__global')
# sys.path.insert(0, '/home/sahar.sagy/Project/PhysioAssist/_process_data/predict_skeleton/model1/poseviz')
# sys.path.insert(0, '/home/sahar.sagy/Project/PhysioAssist/_process_data/predict_skeleton/model1/cameralib')
# sys.path.insert(0, '/home/sahar.sagy/Project/PhysioAssist/_process_data/predict_skeleton/model1/boxlib')

In [2]:
sys.path

['/home/sahar.sagy/Project/PhysioAssist/__global',
 '/home/sahar.sagy/Project/PhysioAssist/_process_data/predict_skeleton/model1',
 '/home/sahar.sagy/miniconda3/envs/proj2/lib/python38.zip',
 '/home/sahar.sagy/miniconda3/envs/proj2/lib/python3.8',
 '/home/sahar.sagy/miniconda3/envs/proj2/lib/python3.8/lib-dynload',
 '',
 '/home/sahar.sagy/.local/lib/python3.8/site-packages',
 '/home/sahar.sagy/miniconda3/envs/proj2/lib/python3.8/site-packages']

In [68]:
import tensorflow_hub as hub
# from __global.skeleton import Skeleton
from skeleton import Skeleton
import tensorflow as tf
import matplotlib
import numpy as np
# matplotlib.use('Agg')
# import matplotlib.pyplot as plt
# from tensorflow.python.ops.numpy_ops import np_config
# np_config.enable_numpy_behavior()
# import poseviz
# import cameralib

In [4]:

model = hub.load('https://bit.ly/metrabs_l')  # or _s
# print(model.joint_names)

2023-08-23 21:50:39.319056: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'cond_raggedfromtensor_1_cond_all_cond_raggedfromtensor_1_range' with dtype int32 and shape [?]
	 [[{{node cond_raggedfromtensor_1_cond_all_cond_raggedfromtensor_1_range}}]]
2023-08-23 21:50:39.391380: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'cond_2_raggedgather_cond_zeros_reshape_cond_2_raggedgather_strided_slice' with dtype int64
	 [[{{node cond_2_raggedgather_cond_zeros_reshape_cond_2_raggedgather_strided_slice}}]]
2023-08-23 21:50:40.652935: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start

In [5]:
def model1_predict_skeleton(frame):
    prediction = model.detect_poses(frame, skeleton='smpl+head_30')
    # todo: need to convert "predicted_skeleton" to match the Skeleton class parameters
    points = prediction['poses3d'][0, :, :]  # num_of_points, 3
    # Create a Skeleton object using attributes_array
    skeleton = None  # Skeleton(*attributes_array)
    return skeleton

In [6]:
image = tf.image.decode_image(tf.io.read_file('images.jpg'))

In [7]:
prediction = model.detect_poses(image, skeleton='smpl+head_30')


2023-08-23 21:52:44.737265: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'image' with dtype uint8 and shape [?,?,3]
	 [[{{node image}}]]
2023-08-23 21:52:44.737400: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'detector_nms_iou_threshold' with dtype float
	 [[{{node detector_nms_iou_threshold}}]]


In [17]:
model.joint_names
prediction['poses3d'][0]

<tf.Tensor: shape=(30, 3), dtype=float32, numpy=
array([[ -11.984706 ,   80.74671  , 2269.056    ],
       [  66.95314  ,  160.89249  , 2286.1023   ],
       [ -76.4341   ,  165.53688  , 2296.643    ],
       [ -16.864922 ,  -14.322537 , 2283.0745   ],
       [ 339.70416  ,  379.78973  , 2113.4133   ],
       [-262.15906  ,  344.5254   , 2027.8352   ],
       [ -32.40275  ,  -89.354164 , 2188.3408   ],
       [ 580.0116   ,  726.3229   , 2101.1887   ],
       [-304.44055  ,  763.5663   , 2020.9932   ],
       [ -40.849792 , -106.10344  , 2141.2683   ],
       [ 634.3988   ,  770.17346  , 1987.4694   ],
       [-337.1505   ,  803.84045  , 1918.0183   ],
       [ -36.440308 , -262.96832  , 2032.0172   ],
       [  34.694817 , -183.5136   , 2072.28     ],
       [-102.61965  , -214.7471   , 2100.227    ],
       [ -34.33421  , -296.9182   , 1953.8757   ],
       [  85.260056 , -133.56331  , 2005.658    ],
       [-194.88875  , -240.96255  , 2076.1223   ],
       [  24.720003 ,  113.512   

In [9]:
print(model.__dict__.keys())

dict_keys(['_self_setattr_tracking', '_self_unconditional_checkpoint_dependencies', '_self_unconditional_dependency_names', '_self_unconditional_deferred_dependencies', '_self_update_uid', '_self_name_based_restores', '_self_saveable_object_factories', 'crop_model', 'joint_names', 'joint_edges', 'detector', 'per_skeleton_indices', 'per_skeleton_joint_names', 'per_skeleton_joint_edges', 'skeleton_joint_indices_table', 'detect_poses', 'detect_poses_batched', 'estimate_poses', 'estimate_poses_batched', 'signatures', 'graph_debug_info', 'tensorflow_version', 'tensorflow_git_version', '_is_hub_module_v1'])


In [30]:
coords = (prediction['poses3d']).numpy()
type(coords)


numpy.ndarray

In [72]:
coord_dict = []

TypeError: 'Skeleton' object does not support item assignment

In [78]:

coord_dict = {}
for i, joint_name in enumerate(model.per_skeleton_joint_names['smpl+head_30'].numpy().astype(str)):
    coord_dict[name_dict[joint_name[:4]]] = coords[0, i]                            
# for a, b in zip(model.per_skeleton_indices['smpl+head_30'].numpy(), model.per_skeleton_joint_names['smpl+head_30'].numpy().astype(str)):
    # index_dict[name_dict[b[:4]]] = coords[0, a]
    # print(b.numpy(), coords[0, a.numpy()])
coord_dict.items()

dict_items([('pelvis', array([ -11.984706,   80.74671 , 2269.056   ], dtype=float32)), ('left_hip', array([  66.95314,  160.89249, 2286.1023 ], dtype=float32)), ('right_hip', array([ -76.4341 ,  165.53688, 2296.643  ], dtype=float32)), ('belly', array([ -16.864922,  -14.322537, 2283.0745  ], dtype=float32)), ('left_knee', array([ 339.70416,  379.78973, 2113.4133 ], dtype=float32)), ('right_knee', array([-262.15906,  344.5254 , 2027.8352 ], dtype=float32)), ('spine', array([ -32.40275 ,  -89.354164, 2188.3408  ], dtype=float32)), ('left_ankle', array([ 580.0116,  726.3229, 2101.1887], dtype=float32)), ('right_ankle', array([-304.44055,  763.5663 , 2020.9932 ], dtype=float32)), ('thorax', array([ -40.849792, -106.10344 , 2141.2683  ], dtype=float32)), ('left_toe', array([ 634.3988 ,  770.17346, 1987.4694 ], dtype=float32)), ('right_toe', array([-337.1505 ,  803.84045, 1918.0183 ], dtype=float32)), ('neck', array([ -36.440308, -262.96832 , 2032.0172  ], dtype=float32)), ('left_claw', arra

In [90]:
prediction['poses3d'][0].numpy()[0]

array([ -11.984706,   80.74671 , 2269.056   ], dtype=float32)

In [ ]:
newS = Skeleton(
    pelvis=coord_dict['pelvis'],
    left_hip=coord_dict['left_hip'],
    right_hip=coord_dict['right_hip'],
    belly=coord_dict['belly'],
    left_knee=coord_dict['left_knee'],
    right_knee=coord_dict['right_knee'],
    spine=coord_dict['spine'],
    left_ankle=coord_dict['left_ankle'],
    right_ankle=coord_dict['right_ankle'],
    thorax=coord_dict['thorax'],
    left_toe=coord_dict['left_toe'],
    right_toe=coord_dict['right_toe'],
    neck=coord_dict['neck'],
    left_claw=coord_dict['left_claw'],
    right_claw=coord_dict['right_claw'],
    head=coord_dict['head'],
    left_shoulder=coord_dict['left_shoulder'],
    right_shoulder=coord_dict['right_shoulder'],
    left_elbow=coord_dict['left_elbow'],
    right_elbow=coord_dict['right_elbow'],
    left_wrist=coord_dict['left_wrist'],
    right_wrist=coord_dict['right_wrist'],
    left_hand=coord_dict['left_hand'],
    right_hand=coord_dict['right_hand'],
    nose=coord_dict['nose'],
    left_eye=coord_dict['left_eye'],
    left_ear=coord_dict['left_ear'],
    right_eye=coord_dict['right_eye'],
    right_ear=coord_dict['right_ear'],
    data=coords
)

In [81]:
newS = Skeleton(
    pelvis=coord_dict['pelvis'],
    left_hip=coord_dict['left_hip'],
    right_hip=coord_dict['right_hip'],
    belly=coord_dict['belly'],
    left_knee=coord_dict['left_knee'],
    right_knee=coord_dict['right_knee'],
    spine=coord_dict['spine'],
    left_ankle=coord_dict['left_ankle'],
    right_ankle=coord_dict['right_ankle'],
    thorax=coord_dict['thorax'],
    left_toe=coord_dict['left_toe'],
    right_toe=coord_dict['right_toe'],
    neck=coord_dict['neck'],
    left_claw=coord_dict['left_claw'],
    right_claw=coord_dict['right_claw'],
    head=coord_dict['head'],
    left_shoulder=coord_dict['left_shoulder'],
    right_shoulder=coord_dict['right_shoulder'],
    left_elbow=coord_dict['left_elbow'],
    right_elbow=coord_dict['right_elbow'],
    left_wrist=coord_dict['left_wrist'],
    right_wrist=coord_dict['right_wrist'],
    left_hand=coord_dict['left_hand'],
    right_hand=coord_dict['right_hand'],
    nose=coord_dict['nose'],
    left_eye=coord_dict['left_eye'],
    left_ear=coord_dict['left_ear'],
    right_eye=coord_dict['right_eye'],
    right_ear=coord_dict['right_ear'],
    data=coords
)

In [87]:
key_list = ['pelv', 'lhip', 'rhip', 'bell', 'lkne', 'rkne', 'spin', 'lank', 'rank', 'thor', 'ltoe', 'rtoe', 'neck', 'lcla', 'rcla', 'head', 'lsho', 'rsho', 'lelb', 'relb', 'lwri', 'rwri', 'lhan', 'rhan', 'nose', 'leye', 'lear', 'reye', 'rear', 'rfoo', 'lfoo', 'htop', 'lthu', 'rthu', 'lfin', 'rfin']
val_list = ['pelvis', 'left_hip', 'right_hip', 'belly', 'left_knee', 'right_knee', 'spine', 'left_ankle', 'right_ankle', 'thorax', 'left_toe', 'right_toe', 'neck', 'left_claw', 'right_claw', 'head', 'left_shoulder', 'right_shoulder', 'left_elbow', 'right_elbow', 'left_wrist', 'right_wrist', 'left_hand', 'right_hand', 'nose', 'left_eye', 'left_ear', 'right_eye', 'right_ear', 'right_foot', 'left_foot', 'head_top', 'left_thumb', 'right_thumb', 'left_finger', 'right_finger']
name_dict = {}
for k, v in zip(key_list[20:], val_list[20:]):
    name_dict[k] = v
    print(f"'{k}': '{v}',")

'lwri': 'left_wrist',
'rwri': 'right_wrist',
'lhan': 'left_hand',
'rhan': 'right_hand',
'nose': 'nose',
'leye': 'left_eye',
'lear': 'left_ear',
'reye': 'right_eye',
'rear': 'right_ear',
'rfoo': 'right_foot',
'lfoo': 'left_foot',
'htop': 'head_top',
'lthu': 'left_thumb',
'rthu': 'right_thumb',
'lfin': 'left_finger',
'rfin': 'right_finger',


In [62]:
unk = []
for i in model.joint_names.numpy().astype(str):
    if (i[:4] in name_dict.keys()):
        print(i, name_dict[i[:4]])
    else:
        unk.append(i)

lhip left_hip
rhip right_hip
bell belly
lkne left_knee
rkne right_knee
spin spine
lank left_ankle
rank right_ankle
thor thorax
ltoe left_toe
rtoe right_toe
neck neck
lcla left_claw
rcla right_claw
head head
lsho left_shoulder
rsho right_shoulder
lelb left_elbow
relb right_elbow
lwri left_wrist
rwri right_wrist
lhan left_hand
rhan right_hand
pelv pelvis
rhip_h36m right_hip
rkne_h36m right_knee
rank_h36m right_ankle
rfoo_h36m right_foot
rtoe_h36m right_toe
lhip_h36m left_hip
lkne_h36m left_knee
lank_h36m left_ankle
lfoo_h36m left_foot
ltoe_h36m left_toe
spin_h36m spine
neck_h36m neck
head_h36m head
htop_h36m head_top
lsho_h36m left_shoulder
lelb_h36m left_elbow
lwri_h36m left_wrist
lthu_h36m left_thumb
lfin_h36m left_finger
rsho_h36m right_shoulder
relb_h36m right_elbow
rwri_h36m right_wrist
rthu_h36m right_thumb
rfin_h36m right_finger
pelv_h36m pelvis
htop_sailvos head_top
neck_sailvos neck
rsho_sailvos right_shoulder
relb_sailvos right_elbow
rwri_sailvos right_wrist
lsho_sailvos left_s

In [64]:
len(unk)

93

In [29]:

def visualize_matplotlib(image, pred, joint_names, joint_edges):
    detections, poses3d, poses2d = pred['boxes'], tf.Variable(pred['poses3d']), pred['poses2d']

    import matplotlib.pyplot as plt
    # noinspection PyUnresolvedReferences
    from mpl_toolkits.mplot3d import Axes3D
    from matplotlib.patches import Rectangle
    plt.switch_backend('Agg')

    fig = plt.figure(figsize=(10, 5.2))
    image_ax = fig.add_subplot(1, 2, 1)
    image_ax.imshow(image)
    for x, y, w, h in detections[:, :4]:
        image_ax.add_patch(Rectangle((x, y), w, h, fill=False))

    pose_ax = fig.add_subplot(1, 2, 2, projection='3d')
    pose_ax.view_init(5, -85)
    pose_ax.set_xlim3d(-1500, 1500)
    pose_ax.set_zlim3d(-1500, 1500)
    pose_ax.set_ylim3d(0, 3000)
    pose_ax.set_box_aspect((1, 1, 1))

    # Matplotlib plots the Z axis as vertical, but our poses have Y as the vertical axis.
    # Therefore, we do a 90° rotation around the X axis:
    poses3d = poses3d.numpy()
    poses3d[..., 1], poses3d[..., 2] = poses3d[..., 2], -poses3d[..., 1]
    poses3d = tf.convert_to_tensor(poses3d, dtype=tf.float32) 
    for pose3d, pose2d in zip(poses3d, poses2d):
        for i_start, i_end in joint_edges:
            image_ax.plot(*zip(pose2d[i_start], pose2d[i_end]), marker='o', markersize=2)
            pose_ax.plot(*zip(pose3d[i_start], pose3d[i_end]), marker='o', markersize=2)
        image_ax.scatter(*pose2d.T, s=2)
        pose_ax.scatter(*pose3d.T, s=2)

    fig.tight_layout()
    plt.show()

In [24]:
poses3d, poses2d = prediction['boxes'], prediction['poses3d']
# poses3d[..., 1]
poses = tf.Variable(poses3d)

In [32]:
joint_names = model.per_skeleton_joint_names['smpl+head_30'].numpy().astype(str)
joint_edges = model.per_skeleton_joint_edges['smpl+head_30'].numpy()
visualize_matplotlib(image, prediction, joint_names, joint_edges)

In [ ]:
           right_shoulder: np.ndarray,
            left_shoulder: np.ndarray,
            right_elbow: np.ndarray,
            left_elbow: np.ndarray,
            right_wrist: np.ndarray,
            left_wrist: np.ndarray,
            right_hip: np.ndarray,
            left_hip: np.ndarray,
            right_knee: np.ndarray,
            left_knee: np.ndarray,
            right_ankle: np.ndarray,
            left_ankle: np.ndarray,